terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region
}

resource "aws_iam_openid_connect_provider" {
  # provider URL
  url = "https://token.actions.githubusercontent.com"
  # audiences
  client_id_list  = ["sts.amazonaws.com"]
  # Generated by navigating to AWS Console > IAM > Identity Providers > Create
  # Identity Provider, selecting 'OpenID Connect', entering the provider URL,
  # and clicking 'Get thumbprint'.
  thumbprint_list = ["1b511abead59c6ce207077c0bf0e0043b1382612"]
}
